CREATE TABLE "wordgrind_quizzes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wordgrind_quizzes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"wordId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"completedAt" timestamp with time zone,
	"result" text,
	"feedback" text NOT NULL,
	"suggestion" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wordgrind_users" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text,
	"email" text,
	"emailVerified" timestamp,
	"image" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"isAdmin" boolean DEFAULT false NOT NULL,
	CONSTRAINT "wordgrind_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "wordgrind_words" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wordgrind_words_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"meaning" varchar(256) NOT NULL,
	"example" varchar(256),
	"pronunciation" varchar(256),
	"synonyms" varchar(64)[],
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"learned" boolean DEFAULT false NOT NULL,
	CONSTRAINT "wordgrind_words_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "wordgrind_quizzes" ADD CONSTRAINT "wordgrind_quizzes_userId_wordgrind_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."wordgrind_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wordgrind_quizzes" ADD CONSTRAINT "wordgrind_quizzes_wordId_wordgrind_words_id_fk" FOREIGN KEY ("wordId") REFERENCES "public"."wordgrind_words"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_tests_idx" ON "wordgrind_quizzes" USING btree ("userId","wordId");--> statement-breakpoint
CREATE INDEX "email_idx" ON "wordgrind_users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "word_idx" ON "wordgrind_words" USING btree ("name");