CREATE TABLE "vocab-grinder_accounts" (
	"userId" text NOT NULL,
	"type" text NOT NULL,
	"provider" text NOT NULL,
	"providerAccountId" text NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" text,
	"scope" text,
	"id_token" text,
	"session_state" text
);
--> statement-breakpoint
CREATE TABLE "vocab-grinder_authenticators" (
	"credentialID" text NOT NULL,
	"userId" text NOT NULL,
	"providerAccountId" text NOT NULL,
	"credentialPublicKey" text NOT NULL,
	"counter" integer NOT NULL,
	"credentialDeviceType" text NOT NULL,
	"credentialBackedUp" boolean NOT NULL,
	"transports" text,
	CONSTRAINT "vocab-grinder_authenticators_credentialID_unique" UNIQUE("credentialID")
);
--> statement-breakpoint
CREATE TABLE "vocab-grinder_user_tests" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vocab-grinder_user_tests_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"wordId" text NOT NULL,
	"spokenSentence" varchar(256) NOT NULL,
	"pronunciationCorrect" boolean DEFAULT false NOT NULL,
	"sentenceCorrect" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "vocab-grinder_sessions" (
	"sessionToken" text PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"expires" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vocab-grinder_user_words" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vocab-grinder_user_words_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"wordId" text NOT NULL,
	"learned" boolean DEFAULT false NOT NULL,
	"quizWins" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vocab-grinder_users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" varchar(256) NOT NULL,
	"username" varchar(256) NOT NULL,
	"emailVerified" timestamp,
	"image" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "vocab-grinder_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "vocab-grinder_verification_tokens" (
	"identifier" text NOT NULL,
	"token" text NOT NULL,
	"expires" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "vocab-grinder_words" (
	"id" text PRIMARY KEY NOT NULL,
	"word" varchar(256) NOT NULL,
	"meaning" varchar(256) NOT NULL,
	"example" varchar(256),
	"pronunciation" varchar(256),
	"synonyms" varchar(64)[],
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "vocab-grinder_words_word_unique" UNIQUE("word")
);
--> statement-breakpoint
ALTER TABLE "vocab-grinder_accounts" ADD CONSTRAINT "vocab-grinder_accounts_userId_vocab-grinder_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."vocab-grinder_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocab-grinder_authenticators" ADD CONSTRAINT "vocab-grinder_authenticators_userId_vocab-grinder_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."vocab-grinder_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocab-grinder_user_tests" ADD CONSTRAINT "vocab-grinder_user_tests_userId_vocab-grinder_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."vocab-grinder_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocab-grinder_user_tests" ADD CONSTRAINT "vocab-grinder_user_tests_wordId_vocab-grinder_words_id_fk" FOREIGN KEY ("wordId") REFERENCES "public"."vocab-grinder_words"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocab-grinder_sessions" ADD CONSTRAINT "vocab-grinder_sessions_userId_vocab-grinder_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."vocab-grinder_users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocab-grinder_user_words" ADD CONSTRAINT "vocab-grinder_user_words_userId_vocab-grinder_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."vocab-grinder_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocab-grinder_user_words" ADD CONSTRAINT "vocab-grinder_user_words_wordId_vocab-grinder_words_id_fk" FOREIGN KEY ("wordId") REFERENCES "public"."vocab-grinder_words"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account.provider_idx" ON "vocab-grinder_accounts" USING btree ("provider","providerAccountId");--> statement-breakpoint
CREATE INDEX "authenticators_idx" ON "vocab-grinder_authenticators" USING btree ("userId","credentialID");--> statement-breakpoint
CREATE INDEX "user_tests_idx" ON "vocab-grinder_user_tests" USING btree ("userId","wordId");--> statement-breakpoint
CREATE INDEX "user_word_idx" ON "vocab-grinder_user_words" USING btree ("userId","wordId");--> statement-breakpoint
CREATE INDEX "email_idx" ON "vocab-grinder_users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "verification_token_idx" ON "vocab-grinder_verification_tokens" USING btree ("identifier","token");--> statement-breakpoint
CREATE INDEX "word_idx" ON "vocab-grinder_words" USING btree ("word");