CREATE TABLE "wordgrind_account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wordgrind_quizzes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wordgrind_quizzes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"wordId" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"completedAt" timestamp with time zone,
	"result" text,
	"feedback" text NOT NULL,
	"suggestion" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "wordgrind_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "wordgrind_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "wordgrind_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"isAdmin" boolean DEFAULT false NOT NULL,
	CONSTRAINT "wordgrind_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "wordgrind_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "wordgrind_words" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wordgrind_words_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" text NOT NULL,
	"name" varchar(256) NOT NULL,
	"meaning" varchar(256) NOT NULL,
	"example" varchar(256),
	"pronunciation" varchar(256),
	"synonyms" varchar(64)[],
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"learned" boolean DEFAULT false NOT NULL,
	CONSTRAINT "wordgrind_words_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "wordgrind_account" ADD CONSTRAINT "wordgrind_account_user_id_wordgrind_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."wordgrind_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wordgrind_quizzes" ADD CONSTRAINT "wordgrind_quizzes_userId_wordgrind_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."wordgrind_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wordgrind_quizzes" ADD CONSTRAINT "wordgrind_quizzes_wordId_wordgrind_words_id_fk" FOREIGN KEY ("wordId") REFERENCES "public"."wordgrind_words"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wordgrind_session" ADD CONSTRAINT "wordgrind_session_user_id_wordgrind_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."wordgrind_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "wordgrind_words" ADD CONSTRAINT "wordgrind_words_userId_wordgrind_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."wordgrind_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_tests_idx" ON "wordgrind_quizzes" USING btree ("userId","wordId");--> statement-breakpoint
CREATE INDEX "email_idx" ON "wordgrind_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "word_idx" ON "wordgrind_words" USING btree ("name");