CREATE TABLE "wordgrind_quiz_responses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "wordgrind_quiz_responses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"quizId" integer NOT NULL,
	"question" text NOT NULL,
	"choices" text[] NOT NULL,
	"userAnswer" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"isCorrect" boolean NOT NULL
);
--> statement-breakpoint
DROP INDEX "user_tests_idx";--> statement-breakpoint
ALTER TABLE "wordgrind_quizzes" ADD COLUMN "score" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "wordgrind_quizzes" ADD COLUMN "totalQuestions" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "wordgrind_quiz_responses" ADD CONSTRAINT "wordgrind_quiz_responses_quizId_wordgrind_quizzes_id_fk" FOREIGN KEY ("quizId") REFERENCES "public"."wordgrind_quizzes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "quiz_responses_quiz_idx" ON "wordgrind_quiz_responses" USING btree ("quizId");--> statement-breakpoint
CREATE INDEX "quizzes_idx" ON "wordgrind_quizzes" USING btree ("userId","wordId");